# Generated by Django 4.1.3 on 2023-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridge", "0002_wallet_relationship_posts_likes_comment_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True,
                default="fb3939e41b303a5fad0c4606c5a2d872226901d3",
                max_length=550,
                null=True,
            ),
        ),
    ]
