# Generated by Django 4.1.3 on 2023-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridge", "0003_alter_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True,
                default="a3530cba6efefe527de237043e6c5c4746681c15",
                max_length=550,
                null=True,
            ),
        ),
    ]
