# Generated by Django 4.1.3 on 2022-12-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridges', models.ManyToManyField(blank=True, related_name='followed_by', to='bridge.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bridge.user')),
            ],
        ),
    ]
