# Generated by Django 4.1.3 on 2023-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridge", "0004_alter_user_is_active_alter_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
