# Generated by Django 4.1.3 on 2023-03-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
