# Generated by Django 4.1.3 on 2023-03-06 13:52

import bridge.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0006_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='document',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=bridge.models.get_user_photo_file_path),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='video',
            field=models.FileField(null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='posts',
            name='document',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.FileField(null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
