# Generated by Django 4.1.3 on 2023-01-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0008_wallet_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.user')),
            ],
        ),
    ]
