# Generated by Django 4.1.3 on 2023-02-18 04:14

import bridge.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0010_user_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_no',
            field=models.CharField(default=bridge.models.get_wallet_account_number, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(re.compile('[A-Z]\\d\\d[A-Z][A-Z]\\d'))], verbose_name='Account Number'),
        ),
    ]
