# Generated by Django 4.1.3 on 2023-04-14 12:07

import bridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0011_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_no',
            field=models.CharField(default=bridge.models.get_wallet_account_number, max_length=10, unique=True, verbose_name='Account Number'),
        ),
    ]
