# Generated by Django 4.1.3 on 2023-02-20 19:22

import bridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0011_wallet_wallet_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to=bridge.models.get_user_photo_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=bridge.models.get_user_photo_file_path),
        ),
    ]
