# Generated by Django 4.1.3 on 2023-04-15 07:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0012_alter_wallet_wallet_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=4200, null=True, size=200),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
