# Generated by Django 4.1.3 on 2023-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0014_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
