# Generated by Django 4.1.3 on 2023-02-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0015_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
