# Generated by Django 4.1.3 on 2023-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0015_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
