# Generated by Django 4.1.3 on 2023-04-19 11:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0016_alter_user_country_alter_user_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=25500, null=True, size=500),
        ),
    ]
