# Generated by Django 4.1.3 on 2023-02-28 16:30

import bridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0017_verificationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=bridge.models.get_user_photo_file_path),
        ),
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=bridge.models.get_user_photo_file_path),
        ),
    ]
