# Generated by Django 4.1.3 on 2023-04-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0020_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridger2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
