# Generated by Django 4.1.3 on 2023-04-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0021_bridges'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
