# Generated by Django 4.1.3 on 2023-03-20 03:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(re.compile('\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}|\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}'), 'Only numbers are allowed in format 000-000-000-000', 'invalid')])),
                ('country', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=1020)),
                ('facebook', models.CharField(max_length=1020)),
                ('instagram', models.CharField(max_length=1020)),
                ('twitter', models.CharField(max_length=1020)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('photos', models.ImageField(upload_to=store.models.get_store_photo_file_path)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('photos', models.ImageField(upload_to=store.models.get_store_photo_file_path)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
